name: Publish
on:
  push:
    branches:
      - main
    paths:
      - '**/CHANGELOG.md'
  workflow_dispatch:
    inputs:
      nocache:
        description: 'Do not rely on existing Docker layer cache'
        default: false
        type: boolean
      docker:
        description: 'Publish Docker package'
        default: false
        type: boolean
      npm:
        description: 'Publish NPM package (immutable)'
        default: false
        type: boolean
      electron:
        description: 'Publish Electron package'
        default: false
        type: boolean
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    # For whatever reason, yaml does not like the full "meta(changelog): Update package versions" string
    # So we check this in two parts
    if: |
      contains(github.event.head_commit.message, 'meta(changelog)') 
      && contains(github.event.head_commit.message, 'Update package versions')
      && inputs.npm
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Setup pnpm & install dependencies
        uses: pnpm/action-setup@v2
        with:
          run_install: true

      - name: Publish to NPM
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          publish: pnpm changeset:publish
          createGithubReleases: true

  docker:
    name: Docker Image
    needs: publish
    runs-on: ubuntu-latest
    if: |
      !cancelled()
      && inputs.docker
      && (needs.publish.result == 'success' || needs.publish.result == 'skipped')
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Docker
        run: docker login --username '${{ github.actor }}' --password-stdin ghcr.io <<< "$GHCR_TOKEN"
        env:
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Docker Context
        run: docker buildx create --driver docker-container --use

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=gha,scope=prod
          no-cache: ${{ inputs.nocache }}
          push: true
          tags: |
            ghcr.io/getsentry/spotlight:latest
            ghcr.io/getsentry/spotlight:${{ github.sha }}

  electron:
    name: Electron Build
    needs: publish
    runs-on: macos-latest
    if: |
      !cancelled()
      && inputs.electron
      && (needs.publish.result == 'success' || needs.publish.result == 'skipped')
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     platform: [x64, arm64]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install deps
        run: pnpm install

      - name: Build packages
        run: pnpm build

      - name: Build Electron
        env:
          APPLEID: ${{ secrets.APPLEID }}
          APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
          TEAMID: ${{ secrets.TEAMID }}
          CERT_PASS: ${{ secrets.CERT_PASS }}
          MAIN_VITE_SENTRY_ORG: ${{ secrets.MAIN_VITE_SENTRY_ORG }}
          MAIN_VITE_SENTRY_PROJECT: ${{ secrets.MAIN_VITE_SENTRY_PROJECT }}
          MAIN_VITE_SENTRY_AUTH_TOKEN: ${{ secrets.MAIN_VITE_SENTRY_AUTH_TOKEN }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
        run: cd packages/electron && pnpm build:mac

      - name: Gets latest created release info
        id: latest_release_info
        uses: gregziegan/fetch-latest-release@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: packages/electron/dist/*.zip
          tag: ${{ steps.latest_release_info.outputs.tag_name }}
          file_glob: true
          make_latest: false
